.PHONY: all

all:

# setup build environment
prepare:
	npm install -g swagger-cli
	go get github.com/deepmap/oapi-codegen/cmd/oapi-codegen

build:
	mkdir -p build

build/wallet.json: wallet/openapi.yaml build
	swagger-cli bundle wallet/openapi.yaml --type json --outfile build/wallet.json

# generate single openapi file
openapi: build/wallet.json

wallet/types.go: build/wallet.json
	oapi-codegen -package wallet -generate types build/wallet.json > wallet/types.go
wallet/client.go: build/wallet.json
	oapi-codegen -package wallet -generate client build/wallet.json > wallet/client.go

# generate go wrappers for openapi
oapi: wallet/types.go wallet/client.go

clean:
	rm -rf build

# delete openapi generated files
distclean: clean
	grep --include="*.go" -rHl . -e "Code generated by github.com/deepmap/oapi-codegen" | xargs -r rm

test: oapi
	go test ./...
