.PHONY: all

all:

# setup build environment
prepare:
	npm install -g swagger-cli
	go get github.com/deepmap/oapi-codegen/cmd/oapi-codegen

# generate single openapi file
openapi:
	mkdir -p build
	swagger-cli bundle wallet/openapi.yaml --type json --outfile build/wallet.json

# generate go wrappers for openapi
oapi: openapi
	oapi-codegen -package wallet -generate types build/wallet.json > wallet/types.go
	oapi-codegen -package wallet -generate client build/wallet.json > wallet/client.go

clean:
	rm -rf build

# delete openapi generated files
distclean: clean
	grep --include="*.go" -rHl . -e "Code generated by github.com/deepmap/oapi-codegen" | xargs -r rm
